/* Content lives here so Spanish and English stay easy to edit in one place. */
const i18n = {
  en: {
    skip:'Skip to content',menuLabel:'Open navigation menu',navHome:'Home',navAbout:'About',navProjects:'Projects',navContact:'Contact',
    heroEyebrow:'Mobile app development',heroTitle:'Building thoughtful mobile experiences.',heroText:'I am a mobile app development professional trained in Flutter, Android and iOS, looking for opportunities to keep building useful software.',heroPrimary:'Explore projects <i class="bi bi-arrow-down-right"></i>',heroSecondary:'Get in touch',portraitAlt:'Portrait of Samuel Maline Alarcón',photoPlaceholder:"Add Samuel's photo in assets/images",portraitCaption:'Open to mobile development opportunities',
    aboutEyebrow:'About',aboutTitle:'A practical background, now focused on mobile.',aboutText:'I bring experience across operations, customer service, travel and logistics to my transition into app development. That background informs the way I work: with care for people, clear communication and a practical approach to solving problems.',aboutText2:'After completing advanced training in programming for mobile devices, I am building my path in software development through mobile projects and continued learning.',transferable:'My experience in customer-facing and operational roles supports a detail-oriented, organised and collaborative way of working.',viewCV:'View CV <i class="bi bi-arrow-up-right"></i>',downloadCV:'<i class="bi bi-download"></i> Download CV',
    projectsEyebrow:'Selected work',projectsTitle:'Projects in progress.',projectsIntro:'HandyPlace and The Phoenix Quest: two Android projects built and tested on a real device.',viewCase:'View case study <i class="bi bi-arrow-up-right"></i>',projectDescription:'Add a concise description of this mobile app project.',projectTech:'Add technologies used',
    contactEyebrow:'Contact',contactTitle:'Let’s talk about what we could build.',contactText:'For a role, a collaboration or simply a conversation about mobile development, feel free to get in touch.',footer:'Built for the next opportunity.',
  },
  es: {
    skip:'Saltar al contenido',menuLabel:'Abrir menú de navegación',navHome:'Inicio',navAbout:'Sobre mí',navProjects:'Proyectos',navContact:'Contacto',
    heroEyebrow:'Desarrollo de aplicaciones móviles',heroTitle:'Creando experiencias móviles pensadas con intención.',heroText:'Soy un profesional formado en desarrollo de aplicaciones móviles con Flutter, Android e iOS, y busco oportunidades para seguir creando software útil.',heroPrimary:'Ver proyectos <i class="bi bi-arrow-down-right"></i>',heroSecondary:'Contactar',portraitAlt:'Retrato de Samuel Maline Alarcón',photoPlaceholder:'Añade mi foto en assets/images',portraitCaption:'Abierto a oportunidades en desarrollo móvil',
    aboutEyebrow:'Sobre mí',aboutTitle:'Una trayectoria práctica, ahora enfocada en móvil.',aboutText:'Aporto experiencia en operaciones, atención al cliente, viajes y logística a mi transición hacia el desarrollo de aplicaciones. Ese recorrido guía mi forma de trabajar: con atención a las personas, comunicación clara y un enfoque práctico para resolver problemas.',aboutText2:'Tras completar formación superior en programación para dispositivos móviles, estoy construyendo mi camino en desarrollo de software mediante proyectos móviles y aprendizaje continuo.',transferable:'Mi experiencia en puestos de atención al cliente y operaciones contribuye a una forma de trabajar organizada, colaborativa y atenta al detalle.',viewCV:'Ver CV <i class="bi bi-arrow-up-right"></i>',downloadCV:'<i class="bi bi-download"></i> Descargar CV',
    projectsEyebrow:'Trabajo seleccionado',projectsTitle:'Proyectos en construcción.',projectsIntro:'HandyPlace y The Phoenix Quest: dos proyectos Android desarrollados y probados en un dispositivo real.',viewCase:'Ver case study <i class="bi bi-arrow-up-right"></i>',projectDescription:'Añade una descripción breve de este proyecto de aplicación móvil.',projectTech:'Añade las tecnologías utilizadas',
    contactEyebrow:'Contacto',contactTitle:'Hablemos de lo que podemos construir.',contactText:'Para una oportunidad, colaboración o simplemente una conversación sobre desarrollo móvil, no dudes en contactar.',footer:'Preparado para la próxima oportunidad.',
  }
};
const projects = [
 {number:'01', title:'HandyPlace', image:'handyplace-logo.webp', tech:'Kotlin · Android · SQLite · PDF', description:{es:'Gestiono varias viviendas, reservas, huéspedes, contratos PDF y resultados económicos desde una sola app Android.',en:'An Android app for managing multiple rentals, bookings, guests, PDF contracts and finances in one place.'}, href:'projects/project-1.html'},
 {number:'02', title:'The Phoenix Quest', image:'phoenix-logo.webp', tech:'Kotlin · Android · Canvas · SoundPool', description:{es:'Una aventura 2D completa: tres niveles, Plumas de Fuego, un hechicero final y dos desenlaces.',en:'A complete 2D adventure with three levels, Fire Feathers, a final sorcerer and two endings.'}, href:'projects/project-2.html'}
];
function renderCards(lang) { const target=document.querySelector('#project-cards'); if(!target)return; const t=i18n[lang]; target.innerHTML=projects.map((project,i)=>`<article class="col-md-6"><div class="project-card"><div class="project-visual project-visual-${project.number}" aria-hidden="true"><img src="assets/images/${project.image}" alt="" loading="lazy"></div><div class="project-card-body"><span class="project-number">Project ${project.number}</span><h3>${project.title}</h3><p>${project.description[lang]}</p><p class="tech-note"><i class="bi bi-tools"></i> ${project.tech}</p><a class="text-link" href="${project.href}">${t.viewCase}</a></div></div></article>`).join(''); }
function applyLanguage(lang){const t=i18n[lang]||i18n.en;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=t[el.dataset.i18n]??el.innerHTML);document.querySelectorAll('[data-i18n-alt]').forEach(el=>el.alt=t[el.dataset.i18nAlt]??el.alt);document.querySelectorAll('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',t[el.dataset.i18nAria]??''));document.querySelectorAll('[data-lang]').forEach(btn=>{const active=btn.dataset.lang===lang;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',active)});renderCards(lang);localStorage.setItem('samuelPortfolioLanguage',lang)}
document.addEventListener('DOMContentLoaded',()=>{const saved=localStorage.getItem('samuelPortfolioLanguage')||'en';applyLanguage(saved);document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>applyLanguage(btn.dataset.lang)));document.querySelector('#year')?.append(new Date().getFullYear());document.querySelectorAll('.nav-link').forEach(link=>link.addEventListener('click',()=>document.querySelector('.navbar-collapse.show')&&bootstrap.Collapse.getOrCreateInstance('#menu').hide()));addEventListener('scroll',()=>document.querySelector('.navbar').classList.toggle('scrolled',scrollY>20),{passive:true})});
