/* Content lives here so Spanish and English stay easy to edit in one place. */
const i18n = {
  en: {
    skip:'Skip to content',menuLabel:'Open navigation menu',navHome:'Home',navAbout:'About',navProjects:'Projects',navContact:'Contact',
    heroEyebrow:'Mobile app development',heroTitle:'Building thoughtful mobile experiences.',heroText:'I am a mobile app development professional trained in Flutter, Android and iOS, looking for opportunities to keep building useful software.',heroPrimary:'Explore projects <i class="bi bi-arrow-down-right"></i>',heroSecondary:'Get in touch',portraitAlt:'Portrait of Samuel Maline Alarcón',photoPlaceholder:"Add Samuel's photo in assets/images",portraitCaption:'Open to mobile development opportunities',
    aboutEyebrow:'About',aboutTitle:'A practical background, now focused on mobile.',aboutText:'I bring experience across operations, customer service, travel and logistics to my transition into app development. That background informs the way I work: with care for people, clear communication and a practical approach to solving problems.',aboutText2:'After completing advanced training in programming for mobile devices, I am building my path in software development through mobile projects and continued learning.',transferable:'My experience in customer-facing and operational roles supports a detail-oriented, organised and collaborative way of working.',viewCV:'View CV <i class="bi bi-arrow-up-right"></i>',downloadCV:'<i class="bi bi-download"></i> Download CV',
    projectsEyebrow:'Selected work',projectsTitle:'Projects in progress.',projectsIntro:'Three mobile app case studies, ready to document the thinking and work behind each build.',viewCase:'View case study <i class="bi bi-arrow-up-right"></i>',projectDescription:'Add a concise description of this mobile app project.',projectTech:'Add technologies used',
    contactEyebrow:'Contact',contactTitle:'Let’s talk about what we could build.',contactText:'For a role, a collaboration or simply a conversation about mobile development, feel free to get in touch.',footer:'Built for the next opportunity.',
    backProjects:'<i class="bi bi-arrow-left"></i> Back to projects',caseType:'Project type',caseRole:'Role',caseDuration:'Duration',caseTech:'Technologies',casePlatform:'Platform',caseOverview:'Project overview',caseChallenge:'The challenge',caseEmpathize:'Empathize',caseDefine:'Define',caseIdeate:'Ideate',casePrototype:'Prototype',caseTest:'Test',caseSolution:'Solution / final product',caseTechnology:'Technology',caseLearned:'What I learned',overviewDescription:'Add a short project description here.',overviewType:'Add project type',overviewRole:'Add role',overviewDuration:'Add duration',overviewTech:'Add technologies',overviewPlatform:'Add platform',challengeText:'Add the problem or need this project was designed to address.',empathyResearch:'User research',empathyResearchText:'Add research findings, interviews or observations here.',empathyAudience:'Target audience',empathyAudienceText:'Add the intended users and their needs here.',defineStatement:'Problem statement',defineStatementText:'Add a clear problem statement here.',definePersona:'Persona, needs & pain points',definePersonaText:'Add persona details and the key needs or pain points here.',ideateIdeas:'Ideas & user flows',ideateIdeasText:'Add brainstorming, sketches, user flows or information architecture here.',prototypeText:'Add prototype images, app screens or development snapshots here.',testText:'Add the testing approach, user feedback and iterations here.',solutionText:'Add final product screenshots, key features and the outcome here.',technologyText:'Add the technologies used and explain why they supported this project.',learnedText:'Add reflections: what was learned, challenges solved and what to improve next time.',previous:'<i class="bi bi-arrow-left"></i> Previous project',next:'Next project <i class="bi bi-arrow-right"></i>',allProjects:'View all projects'
  },
  es: {
    skip:'Saltar al contenido',menuLabel:'Abrir menú de navegación',navHome:'Inicio',navAbout:'Sobre mí',navProjects:'Proyectos',navContact:'Contacto',
    heroEyebrow:'Desarrollo de aplicaciones móviles',heroTitle:'Creando experiencias móviles pensadas con intención.',heroText:'Soy un profesional formado en desarrollo de aplicaciones móviles con Flutter, Android e iOS, y busco oportunidades para seguir creando software útil.',heroPrimary:'Ver proyectos <i class="bi bi-arrow-down-right"></i>',heroSecondary:'Contactar',portraitAlt:'Retrato de Samuel Maline Alarcón',photoPlaceholder:'Añade mi foto en assets/images',portraitCaption:'Abierto a oportunidades en desarrollo móvil',
    aboutEyebrow:'Sobre mí',aboutTitle:'Una trayectoria práctica, ahora enfocada en móvil.',aboutText:'Aporto experiencia en operaciones, atención al cliente, viajes y logística a mi transición hacia el desarrollo de aplicaciones. Ese recorrido guía mi forma de trabajar: con atención a las personas, comunicación clara y un enfoque práctico para resolver problemas.',aboutText2:'Tras completar formación superior en programación para dispositivos móviles, estoy construyendo mi camino en desarrollo de software mediante proyectos móviles y aprendizaje continuo.',transferable:'Mi experiencia en puestos de atención al cliente y operaciones contribuye a una forma de trabajar organizada, colaborativa y atenta al detalle.',viewCV:'Ver CV <i class="bi bi-arrow-up-right"></i>',downloadCV:'<i class="bi bi-download"></i> Descargar CV',
    projectsEyebrow:'Trabajo seleccionado',projectsTitle:'Proyectos en construcción.',projectsIntro:'Tres case studies de aplicaciones móviles, preparados para documentar las decisiones y el trabajo detrás de cada desarrollo.',viewCase:'Ver case study <i class="bi bi-arrow-up-right"></i>',projectDescription:'Añade una descripción breve de este proyecto de aplicación móvil.',projectTech:'Añade las tecnologías utilizadas',
    contactEyebrow:'Contacto',contactTitle:'Hablemos de lo que podemos construir.',contactText:'Para una oportunidad, colaboración o simplemente una conversación sobre desarrollo móvil, no dudes en contactar.',footer:'Preparado para la próxima oportunidad.',
    backProjects:'<i class="bi bi-arrow-left"></i> Volver a proyectos',caseType:'Tipo de proyecto',caseRole:'Rol',caseDuration:'Duración',caseTech:'Tecnologías',casePlatform:'Plataforma',caseOverview:'Resumen del proyecto',caseChallenge:'El reto',caseEmpathize:'Empatizar',caseDefine:'Definir',caseIdeate:'Idear',casePrototype:'Prototipar',caseTest:'Testear',caseSolution:'Solución / producto final',caseTechnology:'Tecnología',caseLearned:'Lo que aprendí',overviewDescription:'Añade aquí una descripción breve del proyecto.',overviewType:'Añade el tipo de proyecto',overviewRole:'Añade el rol',overviewDuration:'Añade la duración',overviewTech:'Añade las tecnologías',overviewPlatform:'Añade la plataforma',challengeText:'Añade el problema o necesidad que este proyecto buscaba resolver.',empathyResearch:'Investigación de usuarios',empathyResearchText:'Añade hallazgos de investigación, entrevistas u observaciones.',empathyAudience:'Público objetivo',empathyAudienceText:'Añade los usuarios previstos y sus necesidades.',defineStatement:'Definición del problema',defineStatementText:'Añade una definición clara del problema.',definePersona:'Persona, necesidades y pain points',definePersonaText:'Añade los detalles de la persona y sus principales necesidades o dificultades.',ideateIdeas:'Ideas y flujos de usuario',ideateIdeasText:'Añade brainstorming, bocetos, flujos de usuario o arquitectura de información.',prototypeText:'Añade imágenes del prototipo, pantallas de la aplicación o avances de desarrollo.',testText:'Añade el enfoque de testing, feedback de usuarios e iteraciones.',solutionText:'Añade screenshots del producto final, funcionalidades principales y resultado.',technologyText:'Añade las tecnologías utilizadas y explica por qué apoyaron este proyecto.',learnedText:'Añade reflexiones: lo aprendido, retos resueltos y qué mejorarías la próxima vez.',previous:'<i class="bi bi-arrow-left"></i> Proyecto anterior',next:'Siguiente proyecto <i class="bi bi-arrow-right"></i>',allProjects:'Ver todos los proyectos'
  }
};
const projectNumbers = ['01','02','03'];
function renderCards(lang) { const target=document.querySelector('#project-cards'); if(!target)return; const t=i18n[lang]; target.innerHTML=projectNumbers.map((n,i)=>`<article class="col-md-6 col-lg-4"><div class="project-card"><div class="project-visual" aria-hidden="true"><i class="bi bi-phone"></i></div><div class="project-card-body"><span class="project-number">Project ${n}</span><h3>Project ${n}</h3><p>${t.projectDescription}</p><p class="tech-note"><i class="bi bi-tools"></i> ${t.projectTech}</p><a class="text-link" href="projects/project-${i+1}.html">${t.viewCase}</a></div></div></article>`).join(''); }
function applyLanguage(lang){const t=i18n[lang]||i18n.en;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=t[el.dataset.i18n]??el.innerHTML);document.querySelectorAll('[data-i18n-alt]').forEach(el=>el.alt=t[el.dataset.i18nAlt]??el.alt);document.querySelectorAll('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',t[el.dataset.i18nAria]??''));document.querySelectorAll('[data-lang]').forEach(btn=>{const active=btn.dataset.lang===lang;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',active)});renderCards(lang);localStorage.setItem('samuelPortfolioLanguage',lang)}
document.addEventListener('DOMContentLoaded',()=>{const saved=localStorage.getItem('samuelPortfolioLanguage')||'en';applyLanguage(saved);document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>applyLanguage(btn.dataset.lang)));document.querySelector('#year')?.append(new Date().getFullYear());document.querySelectorAll('.nav-link').forEach(link=>link.addEventListener('click',()=>document.querySelector('.navbar-collapse.show')&&bootstrap.Collapse.getOrCreateInstance('#menu').hide()));addEventListener('scroll',()=>document.querySelector('.navbar').classList.toggle('scrolled',scrollY>20),{passive:true})});
